project:
  type: website

website:
  title: "MSB205"
  navbar:
    left:
      - href: maps/index.qmd
        text: Maps
      - href: spatmetrics/index.qmd
        text: Spatial Econometrics
      - href: assignment/index.qmd
        text: Assignment

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



